# Generated by Django 2.2.3 on 2019-09-27 18:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('amount_of_money', models.IntegerField(verbose_name='Сумма денег')),
                ('loan_term', models.IntegerField(verbose_name='Срок выдачи (дней)')),
                ('status', models.CharField(default='Ожидает рассмотрения', max_length=30, verbose_name='Статус')),
                ('created', models.DateTimeField(default=datetime.datetime(2019, 9, 27, 18, 57, 0, 758984, tzinfo=utc), verbose_name='Время создания')),
            ],
            options={
                'verbose_name_plural': 'Заявки клиентов',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Телефон')),
                ('name', models.CharField(max_length=30, verbose_name='Имя')),
                ('surname', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчество')),
                ('status', models.CharField(default='Ожидает рассмотрения', max_length=30, verbose_name='Статус')),
                ('created', models.DateTimeField(default=datetime.datetime(2019, 9, 27, 18, 57, 0, 758984, tzinfo=utc), verbose_name='Время создания')),
            ],
            options={
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
