# Generated by Django 2.2.5 on 2019-09-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_request',
            name='status',
            field=models.CharField(default='Ожидает рассмотрения', max_length=30, verbose_name='Статус'),
        ),
    ]
