# Generated by Django 2.2.3 on 2019-09-25 19:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0003_customer_request_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_request',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 19, 14, 17, 361570, tzinfo=utc), verbose_name='Время создания'),
        ),
    ]
