# Generated by Django 2.2.3 on 2019-09-25 19:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('site_pages', '0004_auto_20190925_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_request',
            name='amount_of_money',
            field=models.CharField(max_length=30, verbose_name='Сумма денег'),
        ),
        migrations.AlterField(
            model_name='customer_request',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 25, 19, 39, 33, 819954, tzinfo=utc), verbose_name='Время создания'),
        ),
    ]
